### ISSUE TITLE
Possibility of Adding Record Function

### ISSUE THREAD

**Issue by WhyteFyre** [niqdev/ipcam-view#10]
Hello,
I have been testing this library and I was wondering if you could point me in the right direction on adding recording support for the active video stream.

Regards,
-Dominique

**Comment by niqdev** [comment]
Hi, I will have a look and share it with you here!
If it's worth it I might add a `RecordActivity` and `SnapshotActivity` in the demo or enhance the library.

**Comment by WhyteFyre** [comment]
Thanks for responding! I'm looking into how to use MediaProjection to a MediaRecorder. The main issue is getting a SurfaceView object into there. Would it be possible to grab a BitmapFactory object and record from there?

**Comment by niqdev** [comment]
Could you please add some snippets of code of what would you like or you are trying to implement it or links at some example/resources?
I had a look at some solution, but I didn't have time time yet to test it and implement it, sorry

**Comment by WhyteFyre** [comment]
What I have right now is recordIPCamService (a class, extending Service), which hoping will be instantiated when a button is pressed on the MainActivty. My main problem right now is getting the Intent to be passed to it so that DisplayManager in startRecording() has proper permissions.
I was thinking on creating another class with the permissions methods, for readability purposes.

I will add more info when I have the time.

[recordIPCamService](https://github.com/niqdev/ipcam-view/files/314881/recordIPCamService.txt)

**Comment by niqdev** [comment]
I understood your problem now about SurfaceView, maybe we can think to add other methods that wrap the record functionality in the library directly, in the mean while here few links I've found

* http://mattsnider.com/video-recording-with-mediaprojectionmanager/
* http://bigflake.com/mediacodec
* http://stackoverflow.com/questions/1817742/how-can-i-capture-a-video-recording-on-android

**Comment by WhyteFyre** [comment]
Thanks. I will be looking into those links.

**Comment by niqdev** [comment]
@WhyteFyre did you succeed in the implementation of the record functionality?
If yes would you lie to integrate it in the library? Otherwise I will close the issue.
Thanks

**Comment by niqdev** [comment]
Similar solution to #29

**Comment by niqdev** [comment]
Resolved by #158
