### ISSUE TITLE
Problem visualizing IP camera adding gradle dependency to new app

### ISSUE THREAD

**Issue by vgarces** [niqdev/ipcam-view#11]
Hi @niqdev, i'm trying to use your code in a new APP via the gradle dependency system and can't make it work. I have tried with several cameras to test if I can stream them properly, but none work (including the default one included in your original code). The code always seems to give me "Error" message with any camera I try, but the same cameras work fine in your APP.

What am I doing wrong? i'm doing exactly what you said to include your APP via gradle dependencies, using Android Studio 2.1.2, currently in a fragment activity.

Any help would be appreciated, thanks.

**Comment by niqdev** [comment]
Hi,
I'd like to help you, but do you have any stacktrace for the "error" or could you give me more details about your code?
Sorry if I will answer late but I'm on holiday until next week without laptop and I can't test it directly.

**Comment by vgarces** [comment]
First of all, thanks for the fast reply!

I haven't done proper tracing yet (started working on the code a few days ago), but I can give you some debug output from the app. Whenever a try to see an IP camera stream, the app throws **this error**:

> com.amuinmed.intubappalpha E/ActivityFragment: mjpeg error
>                                                                               java.lang.NullPointerException
>                                                                                   at com.amuinmed.intubappalpha.ActivityFragment.lambda$showCam$0(ActivityFragment.java:48)
>                                                                                   at com.amuinmed.intubappalpha.ActivityFragment.access$lambda$0(ActivityFragment.java:0)
>                                                                                   at com.amuinmed.intubappalpha.ActivityFragment$$Lambda$1.call(Unknown Source)
>                                                                                   at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
>                                                                                   at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
>                                                                                   at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:215)
>                                                                                   at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:107)
>                                                                                   at android.os.Handler.handleCallback(Handler.java:800)
>                                                                                   at android.os.Handler.dispatchMessage(Handler.java:100)
>                                                                                   at android.os.Looper.loop(Looper.java:194)
>                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5434)
>                                                                                   at java.lang.reflect.Method.invokeNative(Native Method)
>                                                                                   at java.lang.reflect.Method.invoke(Method.java:525)
>                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:834)
>                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
>                                                                                   at dalvik.system.NativeStart.main(Native Method)

My app uses a Navigation View, so I'm trying to read the stream in an Activity Fragment, which is called from my Main Activity when I select the correct view. I'm testing it with the **default** type for the stream (haven't implemented native type), without  authentication (credential("", ""), and setting the IP_CAM_URL to "http://plazacam.studentaffairs.duke.edu/mjpg/video.mjpg" directly. I have set **minSdkVersion 15** and **targetSdkVersion 23** in my build.gradle, and use **retrolambda** as well.

Sorry for the really vague question and answer, I'll add more details later on if needed.

And again, thanks for your time and extremely fast reply.

**Comment by niqdev** [comment]
Hi,
could you please copy and paste your code related to the ipcam from MainActivity and ActivityFragment.
I'm expecting it should looks like [IpCamDefaultActivity](https://github.com/niqdev/ipcam-view/blob/master/app/src/main/java/com/github/niqdev/ipcam/IpCamDefaultActivity.java) and [activity_ipcam_default.xml](https://github.com/niqdev/ipcam-view/blob/master/app/src/main/res/layout/activity_ipcam_default.xml)

**Comment by Volvagia27** [comment]
Hi, this is my own account (the one I used before it's a friend's account).

This is the code related to the ipcam from my ActivityFragment `package com.amuinmed.intubappalpha;

    private int TIMEOUT = 5; //seconds

    @BindView(R.id.default_view)
    MjpegView mjpegView;

    @Nullable
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        View v = inflater.inflate(R.layout.navigation_fragment,container,false);
        return v;
    }

    private void showCam(){
        Mjpeg.newInstance()
                .credential("", "")
                .open("http://plazacam.studentaffairs.duke.edu/mjpg/video.mjpg", TIMEOUT)
                .subscribe(
                        inputStream -> {
                            mjpegView.setSource(inputStream);
                            mjpegView.setDisplayMode(DisplayMode.BEST_FIT);
                            mjpegView.showFps(true);
                },
                        throwable -> {
                            Log.e(getClass().getSimpleName(), "mjpeg error", throwable);
                            Toast.makeText(this.getActivity(), "Error", Toast.LENGTH_LONG).show();
                        });
    }

    @Override
    public void onResume() {
        super.onResume();
        showCam();
    }

    @Override
    public void onPause() {
        super.onPause();
        mjpegView.stopPlayback();
    }´

And this is the code related to the layout: 

`<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
xmlns:stream="http://schemas.android.com/apk/res-auto"
xmlns:tools="http://schemas.android.com/tools" android:orientation="vertical"
android:layout_width="match_parent"
android:layout_height="match_parent"
tools:context="com.amuinmed.intubappalpha.ActivityFragment" `>

    <com.github.niqdev.mjpeg.MjpegSurfaceView
        android:id="@+id/default_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        stream:type="stream_default" />
`</RelativeLayout `>

I call my FragmentActivity when a certain item is selected with the code below in my MainActivity:

    private Toolbar toolbar;
    private NavigationView navigationView;
    private DrawerLayout drawerLayout;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);

        navigationView = (NavigationView) findViewById(R.id.navigation_view);

        navigationView.setNavigationItemSelectedListener(new NavigationView.OnNavigationItemSelectedListener() {

            @Override
            public boolean onNavigationItemSelected(MenuItem menuItem) {


                if(menuItem.isChecked()) menuItem.setChecked(false);
                else menuItem.setChecked(true);

                drawerLayout.closeDrawers();

                switch (menuItem.getItemId()){


                    //Replacing the main content with ContentFragment Which is Ipcam View;
                    case R.id.inbox:
                        Toast.makeText(getApplicationContext(),"Inbox Selected",Toast.LENGTH_SHORT).show();
                        ActivityFragment fragment = new ActivityFragment();
                        android.support.v4.app.FragmentTransaction fragmentTransaction = getSupportFragmentManager().beginTransaction();
                        fragmentTransaction.replace(R.id.frame,fragment);
                        fragmentTransaction.commit();
                        return true; ... } 

Again, sorry for the really vague answer, i'm pretty new to android programming. I can add more details if needed.

Thanks for all your help.

**Comment by niqdev** [comment]
Hi,
it seems that in your ActivityFragment the NullPointerException is due to the fact that you are not initializing correctly the view
```java
@Nullable
public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
    View v = inflater.inflate(R.layout.navigation_fragment,container,false);
    // MISSING BIND
    ButterKnife.bind(this, view);
    return v;
}
```
I'm not sure that this is the problem, try to have a look also at [butterknife](http://jakewharton.github.io/butterknife/)

Moreover you can avoid to use this `.credential("", "")` if you don't have any credentials and call it directly like this
```java
Mjpeg.newInstance()
    .open("URL.mjpg", TIMEOUT)
    ...
```
Let me know it it works!

**Comment by Gonsaave** [comment]
Hi, I modified my code like you suggested and it works now! 

The code in my ActivityFragment looks like **this** now:
```Java
 @Nullable
   public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {`
        View v = inflater.inflate(R.layout.navigation_fragment,container,false);
        // View bind
        ButterKnife.bind(this, v);
        return v;
    }
```

About the credentials, that's even better, thanks for the tip. I will keep working on my code and doing some more test, mind if I ask you for help in case I get another problem with your library?

Thanks for all your help and time.

**Comment by niqdev** [comment]
No problem, if I can I will help you!
Just star the project if you like it :wink:
