### ISSUE TITLE
onPause() and onResume() java.lang.IllegalThreadStateException: Thread already started

### ISSUE THREAD

**Issue by disono** [niqdev/ipcam-view#14]
When I tried to put the app in the background and then return to app again this error occurred/showed:

I also tried to clone the source and similar error occured:

java.lang.IllegalThreadStateException: Thread already started
                                                                                                   at java.lang.Thread.checkNotStarted(Thread.java:849)
                                                                                                   at java.lang.Thread.start(Thread.java:1059)
                                                                                                   at com.github.niqdev.mjpeg.MjpegViewDefault._startPlayback(MjpegViewDefault.java:186)
                                                                                                   at com.github.niqdev.mjpeg.MjpegViewDefault._setSource(MjpegViewDefault.java:238)
                                                                                                   at com.github.niqdev.mjpeg.MjpegViewDefault.setSource(MjpegViewDefault.java:283)
                                                                                                   at com.github.niqdev.mjpeg.MjpegSurfaceView.setSource(MjpegSurfaceView.java:67)

@Override
    public void onResume() {
        super.onResume();
        initIPCam();
}

@Override
    public void onPause() {
        camera_viewer.stopPlayback();
}

**Comment by niqdev** [comment]
Hi,
unfortunately what there is under the hood is a bit unclear, so this is the reason of the wrapper library.
Hopefully this [commit](https://github.com/niqdev/ipcam-view/commit/b5549b43a23fcdfb5bbc620eb10be20746aa4fab) fix the issue, but I was unable to replicate it, instead I had a NPE.
Can you tell me please if now version `0.3.4` works? If so, I will update also the demo library.
Thanks

**Comment by disono** [comment]
Hi,
Thanks for the reply, I tried the new commit but it doesn't work, what I did is close the connection when the app is on onPause here is the code I modified:

    void _startPlayback() {
        if (mIn != null && thread != null) {
            mRun = true;
            // clear canvas cache
            mSurfaceView.destroyDrawingCache();
            thread.start();
        }
    }

    void _stopPlayback() {
        mRun = false;
        boolean retry = true;
        while (retry) {
            try {
                // make sure the thread is not null
                if (thread != null) {
                    thread.join();
                }
                retry = false;
            } catch (InterruptedException e) {
            }
        }

        // I add this to close the connection
        if (mIn != null) {
            try {
                mIn.close();
            } catch (IOException e) {
            }
            mIn = null;
        }
    }

Thanks

**Comment by niqdev** [comment]
Great, can you please make a pull request with your fix? if needed revert my changes.

**Comment by disono** [comment]
Yeah sure.

**Comment by niqdev** [comment]
I think you choose the wrong destination branch in #15 (disono wants to merge 16 commits into `java-8-native` from `master`), you should start from the updated master branch and make a pull request on master, not java-8-native, this is why there are conflicts.
Can you please do another pull request with the same fix? I think you can cancel the other one.
Thanks

**Comment by niqdev** [comment]
I've added your changes in this [commit](https://github.com/niqdev/ipcam-view/commit/03346e50004d78303878a68d6e4fc73a82ba4c51) and updated the library to v0.3.5.
Can you tell me if it works now?
Thanks

**Comment by disono** [comment]
Hi thanks but the commit doesn't work, I forgot to add this on my last comment can you update this on MjpegViewDefault.java

void _setSource(MjpegInputStreamDefault source) {
        mIn = source;
        
        // make sure resume is calling _resumePlayback()
        if (!resume) {
            _startPlayback();
        } else {
            _resumePlayback();
        }
    }

Thanks

**Comment by niqdev** [comment]
Version 0.3.6 is out, but I'm still not able to reproduce your error, so just let me know if is ok and then I will update the library in the store when it works for you.
Thanks

**Comment by niqdev** [comment]
@disono sorry, does it work now?
Thanks

**Comment by disono** [comment]
@niqdev yeah it's 100% working!
Thanks.
