### ISSUE TITLE
Fullscreen DisplayMode stretch vs scale

### ISSUE THREAD

**Issue by zaptoopa** [niqdev/ipcam-view#163]
Is it possible in the current state to scale the inputStream instead of stretching it?

I see only three options:
STANDARD(1), BEST_FIT(4), FULLSCREEN(8);

It would be nice if we're able to fit it in width (or height) by scaling.

**Comment by niqdev** [comment]
Thanks for your interest. This project is not under active development, but if you think that there are some missing functionality like the one you are suggesting, please feel free to open a pr and I'll be more than happy to review it and merge it.

Thanks!

**Comment by niqdev** [comment]
Resolved by https://github.com/niqdev/ipcam-view/pull/176

Thanks for your contribution @zaptoopa !
