### ISSUE TITLE
Ability to render to SurfaceTexture

### ISSUE THREAD

**Issue by SalahEddin** [niqdev/ipcam-view#17]
it would be really helpful to know if it's possible to render to an openGL surfaceTexture instead of the MjpegSurfaceView.

**Comment by niqdev** [comment]
Hi! Unfortunately I have no experience at all on openGL, and you?
You are welcome to contribute!

**Comment by niqdev** [comment]
@SalahEddin if you have any improvement with openGL that you would like to share or add to the library feel free to re-open the issue and I will help you to integrate it.
Thanks

**Comment by SalahEddin** [comment]
I have no experience on OpenGL, sorry

**Comment by niqdev** [comment]
Me neither, thanks anyway
