### ISSUE TITLE
Release number not found

### ISSUE THREAD

**Issue by zaptoopa** [niqdev/ipcam-view#179]
Greetings, I'm sorry to report that something went wrong with the release 2.3.2 and release 2.3.3 pipeline. I guess, since release 2.3.2 has failed,  the iteration is not correct anymore. When I use this lib with the latest release version in the gradle dependency of my project, I get the following error:

![v2 3 3](https://user-images.githubusercontent.com/93332963/145173064-3b768d40-7edc-403b-aea6-5a710205fd07.png)

With the version number 2.3.2 everything works fine.

**Comment by niqdev** [comment]
Thanks for reporting this! It looks odd 🤔 I see the artifact [here](https://jitpack.io/#niqdev/ipcam-view/2.3.3) too... @hannesa2 sorry for dragging you in again, do you have the same problem?

I can create a new release if that's necessary. Did you try to compile it from the cli `./gradlew clean build` ?

**Comment by hannesa2** [comment]
I guess you only need more patient.
First time usage triggers the build on jitpack.io and you probably run into this error. Give it some minutes and try it again mostly solves it.

But hold on ! 
https://jitpack.io/com/github/niqdev/ipcam-view/2.3.3/build.log it builds yesterday 
<img width="401" alt="image" src="https://user-images.githubusercontent.com/3314607/145194291-b9e30e6c-5414-4bc3-bd1b-aa7064b9a2f0.png">

Btw, this works for me and I see no issue
`implementation 'com.github.niqdev:ipcam-view:2.3.3'`

**Comment by hannesa2** [comment]
https://jitpack.io/#niqdev/ipcam-view all is fine 

<img width="572" alt="image" src="https://user-images.githubusercontent.com/3314607/145194931-7acfc4a3-e646-4d6f-80ee-58079598ae0b.png">

**Comment by zaptoopa** [comment]
yeah, just tested it again and it works now.
