### ISSUE TITLE
Propagate Network Unavailable Exception

### ISSUE THREAD

**Issue by ariesccv** [niqdev/ipcam-view#21]
Is there any way to have an exception be propagated back to the application in the event that the server is down, so I can use try/catch to handle the exception within my application?

**Comment by niqdev** [comment]
Hi,
I'm not sure if this is what you are looking for, here an [example](https://github.com/niqdev/ipcam-view/blob/master/app/src/main/java/com/github/niqdev/ipcam/IpCamDefaultActivity.java#L57) 

```java
Mjpeg.newInstance()
  .credential(...)
  .open(...)
  .subscribe(
    inputStream -> {
      mjpegView.setSource(inputStream);
      mjpegView.setDisplayMode(calculateDisplayMode());
      mjpegView.showFps(true);
    },
    throwable -> {
      // HERE handle exceptions
      Log.e(getClass().getSimpleName(), "mjpeg error", throwable);
      Toast.makeText(this, "Error", Toast.LENGTH_LONG).show();
  });
```

**Comment by ariesccv** [comment]
Hi,

Here is what I have,
```
private void loadIpCam() {
        rx.Observable<MjpegInputStream> ob;
        Mjpeg myMjpeg = Mjpeg.newInstance();
        myMjpeg.credential("root", "Monte586");

        try
        {
            ob = myMjpeg.open("http://192.168.1.131/axis-cgi/mjpg/video.cgi", TIMEOUT);
            Log.i("MJPEG", "opened");
            ob.subscribe(new Action1<MjpegInputStream>(){
                @Override
                public void call(MjpegInputStream mjpegInputStream) {
                    Log.i("STREAM", "subscribe");
                    mjpegView.setSource(mjpegInputStream);
                    mjpegView.setDisplayMode(DisplayMode.BEST_FIT);
                    mjpegView.showFps(true);
                    Log.i("STREAM", "we are good");
                }
            });
        } catch (Exception e) {
            Log.i("MJPEG", "errror -> " + e.getMessage());
        }
    }
```
I am trying to catch the exception when the server is down.  The above does not catch the exception, been trying for a while with no luck...

**Comment by niqdev** [comment]
I'm not sure the try/catch will work correctly with rxjava.
So few hints, try to use the open [method](https://github.com/niqdev/ipcam-view/blob/master/mjpeg-view/src/main/java/com/github/niqdev/mjpeg/Mjpeg.java#L107) without timeout.
Then you can handle the error or in the `subscribe` or in the `doOnError`

```java
Mjpeg.newInstance()
  .credential(...)
  .open(...)
  .doOnError(throwable -> {
    // HANDLE ALL EXCEPTIONS
  })
  .subscribe(
    inputStream -> {
      ...
    },
    throwable -> {
      // HERE handle exceptions
  });
```
Let me know if it works.
Did you setup the server on your own? If yes, can you tell me the product/library?
I may try to run it and debug it aswell

**Comment by ariesccv** [comment]
I tried the method you suggested, unfortunately it does not work.  I think try/catch does not work with rxjava as you indicated.  I am new to Adroid thus do not know much about rxjava.  I can't get the lamda version to work with my setup, something fail about java 1.8.  I'm using AS 2.2.2, do you have any guide on how to setup java 1.8?

I am using Axis video encoder as the server, Here is the link :  
http://www.axis.com/global/en/products/axis-m7001

**Comment by ariesccv** [comment]
Correction, java 8

**Comment by niqdev** [comment]
Thanks for the link.
I just found [this](http://andersmurphy.com/2015/09/16/setting-up-retrolambda/) tutorial for you, hope it helps. You need both jdk 7 and 8 in your path.
By the way this is [Retrolamba](https://github.com/orfjackal/retrolambda)

**Comment by niqdev** [comment]
@ariesccv did you manage to solve the problem?
Thanks

**Comment by ariesccv** [comment]
I could not make it work with try/catch method but it works using retrolamda.  I notice you have updated the lib, could you tell what changed?
Thanks

**Comment by niqdev** [comment]
I suggest you to avoid try/catch.
Yes the update should fix the thread issue, [here](https://github.com/niqdev/ipcam-view/commit/e3e268eb39022563a3568e5002dfc8bbffb05138) the simple change. On [this](https://github.com/niqdev/ipcam-view/tree/feature/two-cam) branch you can find an example with 2 camera in the same activity

**Comment by niqdev** [comment]
I will close the issue, feel free to re-open it if you have other related problems
