### ISSUE TITLE
Multiple MjpegViews in one activity

### ISSUE THREAD

**Issue by bmachek** [niqdev/ipcam-view#24]
If I put 2 MjpegViews in one activity, one stays black, and the other one is streaming OK.
Both streams work if put alone in a activity.

Is this a known issue? Am I doing something wrong?

Thanks.

**Comment by niqdev** [comment]
Hi, I never tried, could you share the code?
Thanks

**Comment by bmachek** [comment]
Of course :)

`package systems.machek.tankdroid;

import android.os.StrictMode;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.widget.TextView;

import com.github.niqdev.mjpeg.DisplayMode;
import com.github.niqdev.mjpeg.Mjpeg;
import com.github.niqdev.mjpeg.MjpegView;

public class MainCockpit extends AppCompatActivity {

    private MjpegView frontMjpegView;
    private MjpegView turretMjpegView;

    private String frontStatus = "", turretStatus ="";

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main_cockpit);

        frontMjpegView = (MjpegView)findViewById(R.id.frontView);
        turretMjpegView = (MjpegView)findViewById(R.id.turretView);


       Mjpeg.newInstance(Mjpeg.Type.DEFAULT)
                .open(Constants.FRONT_MJPEG_CAM_URL)
                .subscribe(inputStreamFront -> {
                    frontMjpegView.setSource(inputStreamFront);
                    frontMjpegView.setDisplayMode(DisplayMode.BEST_FIT);
                    frontMjpegView.showFps(true);
                });


        Mjpeg.newInstance(Mjpeg.Type.DEFAULT)
                .open(Constants.TURRET_MJPEG_CAM_URL)
                .subscribe(inputStreamTurret -> {
                    turretMjpegView.setSource(inputStreamTurret);
                    turretMjpegView.setDisplayMode(DisplayMode.BEST_FIT);
                    turretMjpegView.showFps(true);
                });


    }

}`

**Comment by niqdev** [comment]
It looks fine, have you tried to debug both the subscribe method? Any exception?

**Comment by niqdev** [comment]
Have you tried to use 2 Fragment for example?

**Comment by bmachek** [comment]
Fragments didn't change anything. There are no exceptions.
Will start the debugger now ;)

**Comment by bmachek** [comment]
So now I finally got the time for doing this ;)
I ran both subscribe methods through the debugger, as far as I could understand what's going on, they look equal, but I'm fairly new to Android development. Maybe someone with more experience could assist.

**Comment by niqdev** [comment]
I found the problem, I'll push the fix now and also and example with multiple view in a separated branch.
The problem was that `private MjpegViewThread thread;` was static... don't ask me why.
As I said all the wrapped code should be rewritten from scratch.

**Comment by niqdev** [comment]
Checkout the branch `feature/two-cam` and give me a feedback please.
I'll update also the project and the library and release a new version.

**Comment by niqdev** [comment]
I published version `0.4.0`

**Comment by bmachek** [comment]
Works like a charm. Many thanks.

**Comment by niqdev** [comment]
If you are working on an open source project, would you be interested to add in the Readme the link to your app?

**Comment by bmachek** [comment]
will do so when it's shareable code ;)

**Comment by bmachek** [comment]
I uploaded the code now.
https://github.com/bmachek/TankDroid
