### ISSUE TITLE
Timeout is not work

### ISSUE THREAD

**Issue by ArtisterLuke** [niqdev/ipcam-view#25]
I try to use Mjpeg.getInsrance()....open(url, timeout).
But this is not work

**Comment by niqdev** [comment]
Hi,
could you please be more clear? Do you have any stacktrace? What is your expected result and what doesn't work? Can you attach any snippet of code if it can make it more clear? Have you tried the demo project with the latest library verion?
Thanks

**Comment by niqdev** [comment]
@ArtisterLuke Since I didn't receive any answer I'll close the issue
