### ISSUE TITLE
Callback function when frame is received

### ISSUE THREAD

**Issue by Selameab** [niqdev/ipcam-view#28]
Hi,
I would like to be able to save a snapshot when a button is pressed.

Is there a function that gets called when a new frame is received?

Thanks

**Comment by niqdev** [comment]
Hi, nope at the moment this functionality is not available, if you find an easy way to integrate or you want to add it to the library let me know.
Thanks

**Comment by Selameab** [comment]
I've sent you a PR

**Comment by niqdev** [comment]
Thanks @Selameab , #29 add this feature
