### ISSUE TITLE
Activity context leaks due to MjpegViewThread

### ISSUE THREAD

**Issue by nairbspace** [niqdev/ipcam-view#3]
Just wanted to give you a heads up that when the `SurfaceHolder` gets passed in `MjpegViewThread` the activity ends up getting leaked. See log below from LeakCanary.

I'm trying to figure out a way to combine the `MjpegInputStream` and `MjpegViewThread` and then update the `SurfaceView` on the main thread. That way the `SurfaceView` doesn't need to get passed in a separate thread. But just like you, I don't understand what's actually going on with all this code.

I'll make a pull request if I figure it out. Thanks for the awesome library!

```
In com.testing.mjpeglib:1.0:1.
* com.testing.mjpeglib.ui.webcam.WebcamActivity has leaked:
* GC ROOT static com.testing.mjpeglib.data.net.stream.MjpegViewDefault.thread
* references com.testing.mjpeglib.data.net.stream.MjpegViewDefault$MjpegViewThread.mSurfaceHolder
* references android.view.SurfaceView$4.this$0 (anonymous implementation of android.view.SurfaceHolder)
* references com.testing.mjpeglib.data.net.stream.MjpegSurfaceView.mContext
* leaks com.testing.mjpeglib.ui.webcam.WebcamActivity instance
```

**Comment by niqdev** [comment]
Hi,
I'm glad you like the library, if you have any suggestions or you have some hints to improve the code I'll be happy to help you and merge your pull request!

**Comment by nairbspace** [comment]
Made a hotfix for now. See pull request: [Activity leak fix #4](https://github.com/niqdev/ipcam-view/pull/4).

**Comment by niqdev** [comment]
Library v0.3.1 is now available if you need it, I will update the app in the store later.
I will close this issue, but if you have any other fix feel free to re-open it.
Thanks!

**Comment by niqdev** [comment]
App version 1.2.1 is now available :smile:
