### ISSUE TITLE
How to implement player callbacks? (buffering, start, stop...)

### ISSUE THREAD

**Issue by nguyenhoanglam** [niqdev/ipcam-view#33]

**Comment by niqdev** [comment]
Hi,
currently the record functionality is not available, there is a similar issue #10 .
At the moment I haven't spare time to add it, if you want feel free to implement it and open a pull request. Contributors are welcome!
Thanks

**Comment by nguyenhoanglam** [comment]
I have another question. If the connection is slow, the MjiegView would be buffering and automatically reconnect (stream) when the connection available?

**Comment by niqdev** [comment]
Nope, I know what you mean, there is no such feature, like back-pressure and as far as I'm aware is directly available in RxJava 2.x while I'm currently using 1.x.
