### ISSUE TITLE
supportRTL=true ?

### ISSUE THREAD

**Issue by jaumard** [niqdev/ipcam-view#37]
When I try to integrate this library it force supportRTL to true https://github.com/niqdev/ipcam-view/blob/master/mjpeg-view/src/main/AndroidManifest.xml#L8

I don't think this should be done as it's a library, it shouldn't change such things (maybe same for allow backup) I can override this in my own AndroidManifest.xml so no big deal ^^

**Comment by niqdev** [comment]
Hi, I actually don't remember if there was any good reason for why is set to `true`, but thanks for pointing out.

**Comment by vvarock** [comment]
Snapshot is not working

**Comment by niqdev** [comment]
@jaumard I'll close this issue, if you have other problem feel free to re-open it.
Thanks
