### ISSUE TITLE
FATAL EXCEPTION: Thread-17 - when I rotate from portrait to landscape

### ISSUE THREAD

**Issue by r3dm4n** [niqdev/ipcam-view#40]
Tried on emulator, genymotion and Nexus 5x. When I rotate the device I sometimes get this error. 
Camera url is not public. 

: FATAL EXCEPTION: Thread-17
                                                                          Process: com.r3dm4n.gradinitaalex, PID: 31635
                                                                          java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.Bitmap com.github.niqdev.mjpeg.MjpegInputStreamDefault.readMjpegFrame()' on a null object reference
                                                                              at com.github.niqdev.mjpeg.MjpegViewDefault$MjpegViewThread.run(MjpegViewDefault.java:129)

**Comment by niqdev** [comment]
Hi, is the demo app that is crashing? This error is a bit confusing `Camera url is not public`. Is it working on the normal emulator or on other devices?

**Comment by r3dm4n** [comment]
Sorry, I meant the camera requires a username and password. 
It's the same behavior on  emulator or real device.

**Comment by niqdev** [comment]
ok about username/password, is the demo app working?

**Comment by r3dm4n** [comment]
Demo app is working without any issues.

**Comment by vvarock** [comment]
Onvif camera support support this demo application?

**Comment by niqdev** [comment]
@r3dm4n is your code public or can you share a snippet of how you integrate it in your code?

@vvarock this library is just a wrapper of 2 existing implementations for read mjpeg streams, I have no idea of supported brands, you need to try by yourself

**Comment by r3dm4n** [comment]
@niqdev issue can be closed. I was doing something wrong. Thanks for the support.

**Comment by niqdev** [comment]
@r3dm4n if your repo is public or app in the store you are welcome to create a pull request and add the link in the readme.
Thanks

**Comment by r3dm4n** [comment]
The app is in the store, code is not public. I'll push the update this next week and add it there.

**Comment by vvarock** [comment]
How to connect in Dlink  933l ip camera
