### ISSUE TITLE
Unable to use ipcam-view with the native support of java 1.8 with Android studio 2.1.1

### ISSUE THREAD

**Issue by ripleyXLR8** [niqdev/ipcam-view#5]
I'm having trouble using ipcam-view with the native support of Android Studio 2.1.1 of Java 1.8.

When i tried to launch the fragment containing the Webcam View I Obtain : 

Caused by: java.lang.IncompatibleClassChangeError: The method 'rx.Observable com.github.niqdev.mjpeg.Mjpeg.com_github_niqdev_mjpeg_Mjpeg_lambda$connect$0(java.lang.String)' was expected to be of type direct but instead was found to be of type virtual (declaration of 'com.github.niqdev.mjpeg.Mjpeg' appears in /data/app/android.application.

In my buidle.graddle (App) I added : 

jackOptions {
            enabled true
       }

and  

compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

in my fragment, the code was : 

MjpegView mjpegView = (MjpegView) view.findViewById(R.id.WebCam_View);

```
    int TIMEOUT = 5; 

    Mjpeg.newInstance()
            //.credential("USERNAME", "PASSWORD")
            .open("URL", TIMEOUT)
            .subscribe(inputStream -> {
                mjpegView.setSource(inputStream);
                mjpegView.setDisplayMode(DisplayMode.BEST_FIT);
                mjpegView.showFps(true);
            });
```

Thank you for your help and for the work you have done on this project.

Best regards

Richard

**Comment by niqdev** [comment]
Hi,
I've created a new branch [java-8-native](https://github.com/niqdev/ipcam-view/tree/java-8-native), updated the [build.gradle](https://github.com/niqdev/ipcam-view/blob/java-8-native/app/build.gradle) and followed [this](https://developer.android.com/preview/j8-jack.html) and [this](https://developer.android.com/preview/setup-sdk.html) 

> Android N introduces support for Java 8 language features that you can use when developing apps that **target Android N**
...
To start using these features, you need to download and set up Android Studio 2.1 and the **Android N Preview SDK**

is clear that Java 8 native works only with Android N, i.e.
```
minSdkVersion 'N'
targetSdkVersion 'N'
```
while I would like to support the wider range of devices.

Anyway I tried to use
```
jackOptions {
  enabled true
}
```
but I've have the following error `Error: Cannot get property 'destinationDir' on null object` and I don't understand why.
Did you have the same error? If you checkout this branch you can have a look if you want.

By the way, if you need java 8 features, at least you could use [retrolambda](https://github.com/orfjackal/retrolambda) and [Lightweight-Stream-API
](https://github.com/aNNiMON/Lightweight-Stream-API)

**Comment by ripleyXLR8** [comment]
I had these error before switching my buildtools version "buildToolsVersion "24.0.0-rc3""

**Comment by niqdev** [comment]
I just tested on java-8-branch but the project still don't compile with
```
jackOptions {
  enabled true
}
```
and 
```
compileSdkVersion 'android-N'
buildToolsVersion '24.0.0-rc3'
```
and I have the same error `Error: Cannot get property 'destinationDir' on null object`. Could you try to confirm if it works for you or not?

About the second question I've checked and yes, actually there is only one lambda in `Mjpeg#connect`, but to be honest if you suggest that it can help you I could think to remove retrolambda, is wasted here. What do you think?

**Comment by ripleyXLR8** [comment]
I tried the java-8-native branch.
It doesn't work first, it cannot start on my "N preview" emulator, I don't know why it doesn't allow it.

I had to change to
compileSdkVersion 23
minSdkVersion 23
targetSdkVersion 23

Then it works without error or warning.

**Comment by niqdev** [comment]
I think we should wait for a stable `buildToolsVersion` and then we try again. Do you agree?

**Comment by ripleyXLR8** [comment]
I think so.... I will use retrolambda in the meantime.

**Comment by niqdev** [comment]
:+1:

**Comment by ingaramop** [comment]
Hi  @niqdev, I have been trying to build a simple app to try this wrapper with no success.
First, I tried to use it with java 1.8, getting the same issue with jackOptions.
Then, I tried using Retrolambda and Lightrweight-Stream-Api as sugested above, but I keep getting errors.

I am new to Android, so maybe I am making some silly mistake. Could you take a look at this and tell me what am I doing wrong?
https://github.com/ingaramop/MjpegPlayerTest

**Comment by niqdev** [comment]
Hi @ingaramop!

Yes sure, so first of all [here](https://github.com/ingaramop/MjpegPlayerTest/blob/master/app/src/main/res/layout/activity_main.xml) you should give a name at MjpegSurfaceView i.e. `android:id="@+id/VIEW_NAME"` for example could be `android:id="@+id/myMjpegView"`

Then, because you are not using [butterknife](http://jakewharton.github.io/butterknife/), if I'm correct you should add in the [activity#onCreate](https://github.com/ingaramop/MjpegPlayerTest/blob/master/app/src/main/java/com/example/root/mjpegplayertest/MainActivity.java) something like
```java
mjpegView = (MjpegSurfaceView) findViewById(R.id.myMjpegView);
```
I'm not sure that will work straight, so let me know if you have any other problem.

**Comment by ingaramop** [comment]
@niqdev, It worked straightforward with those changes. Thanks!

**Comment by marconealberto** [comment]
so.. I still get the error "Error:Cannot get property 'destinationDir' on null object", tried to use @ingaramop 's code that allegedly worked for him.
What should I exactly do to make it work?

**Comment by niqdev** [comment]
Hi @marconealberto , I've updated all libraries with the latest version available, can you tell me now if the project compiles and you are able to run the demo app?
Thanks

**Comment by niqdev** [comment]
The project have been updated with the latest `sdk` and `support` libraries version
