### ISSUE TITLE
regarding ip cam url issue 

### ISSUE THREAD

**Issue by rajlee5129** [niqdev/ipcam-view#54]
good evening sir,i am trying to implement ip cam live stream but i can not understand how to take ip cam url form blow my ip cam web page view inspect element data.

<embed src="swfs/StrobeMediaPlayback.swf" width="640" height="352" quality="high" bgcolor="#000000" name="StrobeMediaPlayback" allowfullscreen="true" pluginspage="http://www.adobe.com/go/getflashplayer" flashvars="&amp;src=rtmp://192.168.1.5:1935/flash/12:YWRtaW46YWRtaW4=&amp;autoHideControlBar=true&amp;streamType=live&amp;autoPlay=true" type="application/x-shockwave-flash">

so please help me to solve this problem.

**Comment by niqdev** [comment]
Hi, not sure how much I can help on this, in the [wiki](https://github.com/niqdev/ipcam-view/wiki) there is an example, but it really depends from your camera

**Comment by rajlee5129** [comment]
ok i will look into this issue
