### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by Poussinou** [niqdev/ipcam-view#62]
F-Droid received a [Request For Packaging](https://gitlab.com/fdroid/rfp/issues/85) for your app.
To be build by F-Droid, we need to find a way to build everything from source. Could you help us to do so? Here are the problematic prebuilt libraries:

> ERROR: Found shared library at mjpeg-view/src/main/jniLibs/x86/libImageProc.so
ERROR: Found shared library at mjpeg-view/src/main/jniLibs/mips/libImageProc.so
ERROR: Found shared library at mjpeg-view/src/main/jniLibs/armeabi-v7a/libImageProc.so
ERROR: Found shared library at mjpeg-view/src/main/jniLibs/armeabi/libImageProc.so

**Comment by niqdev** [comment]
Hi, thanks for including the package on F-Droid.
So there is a [script](https://github.com/niqdev/ipcam-view/blob/master/compileJni.sh) to build those libraries, but unfortunately at the moment is not integrated with any CI/CD and they were built manually.
Consider also that with the help of @amadeu01 we are looking at #59 and #60 which means a full rewrite of the project in Kotlin, so not sure if is worth fix this issue now.

Where those errors came from? How is the build process working to release the app on F-Droid?

**Comment by niqdev** [comment]
I can create a PR for that now if you want, is not a big deal. Regarding the rewrite is not something that is going to happen any time soon, just considering how and what to do.

**Comment by Rudloff** [comment]
Well, if building the libraries is as easy as running this script, I guess I can work on packaging the current version.

**Comment by Rudloff** [comment]
Are these prebuilt libraries really necessary?
It seems I can build and run the demo app even if I remove them.

**Comment by niqdev** [comment]
No, I was planning to remove it before considering a full rewrite. The native implementation is broken and never got time to try to fix it. If it compiles and work just ignore those files

**Comment by Rudloff** [comment]
Oh OK so we can totally package this on F-Droid then.

**Comment by niqdev** [comment]
Nice, I'll merge the PR then, is that enough?

**Comment by Rudloff** [comment]
If you are talking about https://github.com/niqdev/ipcam-view/pull/63, I don't think we strictly need it, it's just something our linter complains about.

So I think you should merge it (for security reasons) but it is not a requirement.

**Comment by niqdev** [comment]
Got it, is correct the command I've added in the PR to generate the hash? or how did you get that and what should I run next time I bump the version?

**Comment by niqdev** [comment]
@Rudloff last question, which are the criteria to add an app on F-Droid other then being open source? I have another [app](https://github.com/openwebnet/openwebnet-android) that you might be interested in...

**Comment by Rudloff** [comment]
You can check our [inclusion policy](https://f-droid.org/docs/Inclusion_Policy/).

Feel free to open a [request](https://gitlab.com/fdroid/rfp/issues/new) for your other app if it meets the criteria.

**Comment by niqdev** [comment]
Awesome, thanks!

**Comment by niqdev** [comment]
Yep, I'm going to release the latest version now, I'll tell you when is done

**Comment by niqdev** [comment]
I've released app `v.1.7.0`, let me know if works now

**Comment by Rudloff** [comment]
It works, thanks!
