### ISSUE TITLE
Crashes on Android studio v3.1.4

### ISSUE THREAD

**Issue by FerialMuhammad** [niqdev/ipcam-view#76]
Hi there,
I downloaded the entire project just to make sure I have everything right,but when I open it from android studio v3.1.4 the whole program just crashes and closes. what do you think might be the problem?
will getting an older version do the trick? and if so which one would be better?
P.S. I tried it on windows 8.1 and on 10

**Comment by niqdev** [comment]
Hi, sorry for the late response, as soon as I'll have time I'll investigate this and give you a feedback.
Thanks

**Comment by Hannan321** [comment]
Mr Niqdev we will be grateful if you could upload a tutorial of this app which tells us how to build this kind of IP cam android apps

**Comment by EmerickH** [comment]
Hello,
I've got the same problem on Android Studio 3.4.2, any idea why is it crashing?

**Comment by niqdev** [comment]
Thanks for the feedback and sorry for the late replay, I'll close the issue then!
