### ISSUE TITLE
Build is broken

### ISSUE THREAD

**Issue by hannesa2** [niqdev/ipcam-view#97]
#84 brokes the build

<img width="469" alt="image" src="https://user-images.githubusercontent.com/3314607/112747041-2c4b9180-8fb3-11eb-9fc8-58696c757ce2.png">

**Comment by PanderMusubi** [comment]
Does this fix it? https://github.com/niqdev/ipcam-view/pull/102

**Comment by hannesa2** [comment]
yes

**Comment by hannesa2** [comment]
close #102
